version: '3'

services:
  phpapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: phpapp:123
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
    container_name: myphpapp-app
  
  db:
    image: mysql:latest
    restart: always
    environment
      MYSQL_ROOT_PASSWORD: somepass
    container_name: myphpapp-db